Update patch set 36
Patch Set 36:

> Patch Set 36:
> 
> @Luca Milanesio i run docker run gerritforge/gerrit-ci
> 
> then it starts to fail with
> 
> INFO: I/O exception (shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request: tcp protocol is not supported
> Dec 22, 2016 4:38:18 PM shaded.org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request
> Dec 22, 2016 4:38:18 PM shaded.org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request: tcp protocol is not supported
> Dec 22, 2016 4:38:18 PM shaded.org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request
> Dec 22, 2016 4:38:18 PM shaded.org.apache.http.impl.execchain.RetryExec execute
> INFO: I/O exception (shaded.org.apache.http.conn.UnsupportedSchemeException) caught when processing request: tcp protocol is not supported
> Dec 22, 2016 4:38:18 PM shaded.org.apache.http.impl.execchain.RetryExec execute
> INFO: Retrying request
> Dec 22, 2016 4:38:18 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
> WARNING: Bad template 'gerrit-ci-slave-buck' in cloud 'dockerhost': 'shaded.org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported'. Trying next template...
> javax.ws.rs.ProcessingException: shaded.org.apache.http.conn.UnsupportedSchemeException: tcp protocol is not supported
>         at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:490)
>         at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
> 
> im using docker toolbox as i doint want to enable hyper-v

I run:
docker run -ti -p 8080:8080 gerritforge/gerrit-ci

And then executed your change to generate jobs ... and I've got:
yaml.parser.ParserError: while parsing a block collection
  in "/var/jenkins_home/jobs/gerrit-ci-scripts-manual/workspace/jenkins/gerrit-buck-bazel-plugin-scala-provider.yaml", line 4, column 7
expected <block end>, but found '<block mapping start>'
  in "/var/jenkins_home/jobs/gerrit-ci-scripts-manual/workspace/jenkins/gerrit-buck-bazel-plugin-scala-provider.yaml", line 5, column 12
Build step 'Execute shell' marked build as failure

There is a bug at line 5, column 12 of the gerrit-buck-bazel-plugin-scala-provider.yaml. 

Are you sure you've got the skills to get this change done properly?

Patch-set: 36