Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> > Patch Set 8:
> > 
> > > Patch Set 8: Verified-1
> > > 
> > > The gitiles-plugin (and maybe others) does not seem to build with Java11: http://paste.openstack.org/show/S4mQrrjwMQ88ZKH83k5b/
> > 
> > Looking into your log:
> > 
> > plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:141: error: method does not override or implement a method from a supertype
> >   @Override
> >   ^
> > plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:143: error: cannot find symbol
> >     return delegate.getIdentifier();
> >                    ^
> >   symbol:   method getIdentifier()
> > 
> > It sounds like a inconsistency between used (outdated) JGit version (that hasn't added yet  Repostory#getIdentifier() method) but already adjusted plugin version. So that the problem is not really related to Java 11.
> 
> This should not be the case since gitiles is a core repo; if there was a breaking change we would have caught it.
> 
> It looks like in the build the plugin revisions are getting modified:
>  
>  HEAD is now at db3a788e4a... Bazel: Add support for toolchain_java11
>  M	plugins/delete-project
>  M	plugins/gitiles
>  M	plugins/plugin-manager
>  M	plugins/replication

Well, the plugin version is correct, on master, this change was merged 3 days ago: [1]. So the question remains, why JGit version is outdated? Are you building master? I cannot reproduce this problem locally. If I cherry-pick the Java 11 commit (Ib67dcc50a43f998bc8f5a363a8f681e3693d1f26) on top of this commit: (235f3f7689efe34f2681a67524b3adf1358dac6c) the build works as expected:

   $ b10 build --host_javabase=@bazel_tools//tools/jdk:remote_jdk11  --javabase=@bazel_tools//tools/jdk:remote_jdk11 --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 :release
  [...]
  arget //:release up-to-date:
  bazel-bin/release.war
INFO: Elapsed time: 265.876s, Critical Path: 180.42s
INFO: 949 processes: 2 remote cache hit, 117 linux-sandbox, 830 worker.
INFO: Build completed successfully, 986 total actions

Can you reproduce the problem locally? What is the difference with the build on CI?


* [1] https://gerrit-review.googlesource.com/c/plugins/gitiles/+/226656

Patch-set: 8
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>