Update patch set 5
Patch Set 5: Verified+1

I observed one issue, but further testing showed, that it is unrelated to this change. If in the Gerrit-verifier-pipeline the downstream jobs (Gerrit-bazel-verifier or Gerrit-codestyle) are aborted, before they are started on a slave node, the pipeline fails with:

java.lang.NullPointerException: Cannot invoke method getAbsoluteUrl() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:160)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:162)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.prepareBuildsForMode(WorkflowScript:179)

Since this is not a normal use case, this can be fixed later, if at all.

Otherwise, the pipeline works and blue ocean opens correctly in the browser.

Patch-set: 5
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1065256 <1065256@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1