Update patch set 5
Patch Set 5: Verified-1

Fails again:
java.lang.RuntimeException: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

You need to change the Dockerfile to install the Android SDK and define the Docker env variable pointing to it

Patch-set: 5
Label: Verified=-1