Update patch set 2
Patch Set 2: Verified-1

(1 comment)

It looks like that running from within the same GCP account and application is still not enough: 
ERROR: Failed to query remote execution capabilities: PERMISSION_DENIED: Request had insufficient authentication scopes.

We would need also to:
- Install the GCloud CLI
- Pass to the script a GCloud authentication service token
- Login with the service token

It looks like being inside GCP or not really doesn't make so much difference in terms of authentication, unless I'm missing something.

@Han-Wen @Philipp should a call from within the same domain (GCloud compute) still require explicit authentication for running a Bazel remote build on RBE?

Patch-set: 2
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1