Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> > Patch Set 8:
> > 
> > > Patch Set 8: Verified-1
> > > 
> > > The gitiles-plugin (and maybe others) does not seem to build with Java11: http://paste.openstack.org/show/S4mQrrjwMQ88ZKH83k5b/
> > 
> > Looking into your log:
> > 
> > plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:141: error: method does not override or implement a method from a supertype
> >   @Override
> >   ^
> > plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:143: error: cannot find symbol
> >     return delegate.getIdentifier();
> >                    ^
> >   symbol:   method getIdentifier()
> > 
> > It sounds like a inconsistency between used (outdated) JGit version (that hasn't added yet  Repostory#getIdentifier() method) but already adjusted plugin version. So that the problem is not really related to Java 11.
> 
> This should not be the case since gitiles is a core repo; if there was a breaking change we would have caught it.
> 
> It looks like in the build the plugin revisions are getting modified:
>  
>  HEAD is now at db3a788e4a... Bazel: Add support for toolchain_java11
>  M	plugins/delete-project
>  M	plugins/gitiles
>  M	plugins/plugin-manager
>  M	plugins/replication

Yes, I noticed that as well. This is gone after now using the new patch set of the davidO's change. So it was probably based on an old commit on master. Since I have to checkout the change manually to test it, I checked out the history of that patch set, which was not current.

The job is not finished yet, but now past the point of this failure.

Patch-set: 8
Reviewer: Gerrit User 1065256 <1065256@173816e5-2b9a-37c3-8a2e-48639d4f1153>