Update patch set 3
Patch Set 3:

I enabled this for builder number 61. For reference: these were the steps:
* create the worker pool (for some reason it went missing on the api-xxx project).
gcloud alpha remote-build-execution worker-pools  create  default  --project=api-project-164060093628 --instance=default_instance --worker-count=20  --machine-type=e2-standard-4     --disk-size=200

* Enable all APIs on the service account. Now, the scopes list https://www.googleapis.com/auth/cloud-platform
$ gcloud beta compute instances --project=api-project-164060093628  set-scopes --scopes=cloud-platform gerrit-ci-workers-62

* Enable RBE on the service account: gcloud projects add-iam-policy-binding api-project-164060093628  --role roles/remotebuildexecution.artifactCreator --member serviceAccount:164060093628@project.gserviceaccount.com
On machine 61, I can now run 
  bazel build --remote_instance_name=projects/api-project-164060093628/instances/default_instance --config=remote javatests/com/google/gerrit/acceptance/server/change/...

which now fails with 
ERROR: /home/hanwen/gerrit/antlr3/BUILD:4:1: Executing genrule //antlr3:query failed (Exit 127)/bin/bash: mktemp: command not found

I am not sure if this is related to the new machine type I picked (e2-standard-4) or because we are now building on a different Ubuntu image.

Patch-set: 3
Reviewer: Gerrit User 1024147 <1024147@173816e5-2b9a-37c3-8a2e-48639d4f1153>