Update patch set 1
Patch Set 1: Verified-1

The new version doesn't build:

  $ bazel build --workspace_status_command=`pwd`/status.sh //buildifier
  Starting local Bazel server and connecting to it...
  INFO: Analyzed target //buildifier:buildifier (52 packages loaded, 7125 targets configured).
  INFO: Found 1 target...
  ERROR: Process exited with status 127: Process exited with status 127
  /bin/sh: /home/davido/projects/buildtools/status.sh: No such file or directory

It seems that status.sh was replaced with status.py in: [1].

* [1] https://github.com/bazelbuild/buildtools/commit/e39fbfad883c74d5ee4638c734f406b2be555bc3

Patch-set: 1
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1065256 <1065256@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1