Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> Fails, see the error below:
> ---8<---8<--- Start of log, file at /home/jenkins/.cache/bazel/_bazel_jenkins/f26dd752773e21141518b9f2c4bad617/bazel-workers/worker-1-Javac.log ---8<---8<---
> Unrecognized option: --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ---8<---8<--- End of log ---8<---8<---

Hmm.  Do we need to upgrade to 0.16 to make this work?  If that's the case, it's probably better to wait for 0.17 to be released.

Patch-set: 1
Reviewer: Gerrit User 1011123 <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>