Update patch set 1
Patch Set 1:

This broke compatibility with future Bael releases (bazel 3.0), see: [1]:

  ERROR: --ram_utilization_factor is deprecated. Please use --local_ram_resources=HOST_RAM*<float>

According to Han-Wen comments on the issue linked to that change, is shouldn't be needed. IMO, that change should be reverted now.

* [1] https://gerrit-review.googlesource.com/c/gerrit/+/261974

Patch-set: 1
CC: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>