Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Thanks for trigger the jenkins job, Luca. https://gerrit-review.googlesource.com/c/plugins/cloud-notifications/+/173591 fixes the build issues in stable-2.15
> 
> Failed again:
> https://gerrit-ci.gerritforge.com/job/plugin-cloud-notifications-bazel-master-stable-2.15/1/console




Luca, sorry for bother you, but I don't understand the Jenkins error. Why is Jenkins fetching the master branch of the cloud notifications instead of the stable-2.15?


For example, for this error in the Jenkins console job (https://gerrit-ci.gerritforge.com/job/plugin-cloud-notifications-bazel-master-stable-2.15/1/console):

13:32:00 plugins/cloud-notifications/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java:46: error: package com.google.gerrit.server.account.ProjectWatches does not exist
13:32:00 import com.google.gerrit.server.account.ProjectWatches.NotifyType;

That import is only in master

https://gerrit.googlesource.com/plugins/cloud-notifications/+/master/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java#46

but not in 2.15

https://gerrit.googlesource.com/plugins/cloud-notifications/+/stable-2.15/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java#48



And it happens the same for 2.14 branch (https://gerrit-ci.gerritforge.com/job/plugin-cloud-notifications-bazel-master-stable-2.14/6/console), https://gerrit.googlesource.com/plugins/cloud-notifications/+/stable-2.14/src/main/java/com/ruesga/gerrit/plugins/fcm/handlers/EventHandler.java#42



I have build locally with bazel against every branch and all (master, stable-2.15 and stable-2.14) built correctly


I removed from the BUILD script on master and stable-2.15 the "Implementation-Version" property, because gerrit was complaining about duplicates (since the bazel build introduces its own one), but stable-2.14 still have it, so I don't think that's the cause of the problem.

Thanks in advance.

Patch-set: 1
Reviewer: Jorge Ruesga <1029647@173816e5-2b9a-37c3-8a2e-48639d4f1153>