Update patch set 8
Patch Set 8:

> Patch Set 8: Verified-1
> 
> The gitiles-plugin (and maybe others) does not seem to build with Java11: http://paste.openstack.org/show/S4mQrrjwMQ88ZKH83k5b/

Looking into your log:

plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:141: error: method does not override or implement a method from a supertype
  @Override
  ^
plugins/gitiles/src/main/java/com/googlesource/gerrit/plugins/gitiles/FilteredRepository.java:143: error: cannot find symbol
    return delegate.getIdentifier();
                   ^
  symbol:   method getIdentifier()

It sounds like a inconsistency between used (outdated) JGit version (that hasn't added yet  Repostory#getIdentifier() method) but already adjusted plugin version. So that the problem is not really related to Java 11.

Patch-set: 8
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>