Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> Nice, I replaced the usage of javadoc from JDK8 with javadoc from JDK11 (will upload a fix in a moment), just to realize, that I can now reproduce your breakage:
> 
>  $ external/remotejdk11_linux/bin/javadoc -Xdoclint:-missing -protected -encoding UTF-8
>  [...]
>   ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/extensions/BUILD:40:1: error executing shell command: '/bin/bash -c TZ=UTC && export TZ && rm -rf bazel-out/k8-fastbuild/bin/java/com/google/gerrit/extensions/extension-api-javadoc.zip.source && mkdir bazel-out/k8-fastbuild/bin/java/com/google/gerrit/e...' failed (Exit 1)
> javadoc: error - Error fetching URL: https://download.eclipse.org/jgit/site/5.4.3.201909031940-r/apidocs/
> 1 error
> 
> Conclusion: the javadoc from JDK 11 is much stricter then javadoc from JDK 8, and bumped the severity to error if apidoc cannot be found.
> 
> So that we have two different problems:
> 
> * Wrong javadoc is used (will upload a fix in moment)
> * Find a proper apidoc for JGit release (still should be figured out)

I didn't yet upload javadoc for latest JGit releases since Eclipse Foundation changed policies for access to download server, hence I have to write a new Jenkins job to deploy the javadoc which I did via ssh so far, will try to do that over the weekend

Patch-set: 12
Reviewer: Gerrit User 1004034 <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>