Default git http username and password to empty strings
Not having a default for Gerrit http username and password causes
Jenkins to fail due to:

```
IllegalArgumentException: Null value not allowed as an environment
variable
```

Default gerrit http username and password to empty strings and check for
empty values to decide whether to use vault defaults.

Bug: Issue 14194
Change-Id: Ic719dfcde11e00f1bb272b2ff7954dc47fc03e27