Revert "Bazel: Activate RBE configuration on GCP"
This reverts commit 25999b12a38fc65b09a55cdb16f89833b65fe612.

Reason for revert: RBE build is failing on GCP.

Error message is:

ERROR: Failed to init auth credentials: The Application Default
Credentials are not available. They are available if running in
Google Compute Engine. Otherwise, the environment variable
GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file
defining the credentials.

Change-Id: I7312ff6d8c2fb1a3993b3d5ec1307ae28009b119