Update patch set 12
Patch Set 12:

> Patch Set 12:
> 
> The build still doesn't work on the CI. I get this error:
> 
>   ERROR: /Users/d073103/working_dir/gerrit-dev/opensource/gerrit- 
>   master/java/com/google/gerrit/extensions/BUILD:40:1: error executing shell command: 
>   '/bin/bash -c TZ=UTC && export TZ && rm -rf bazel-out/darwin- 
>   fastbuild/bin/java/com/google/gerrit/extensions/extension-api-javadoc.zip.source && mkdir 
>   bazel-out/darwin-fastbuild/bin/java/com/google/...' failed (Exit 1)
>   javadoc: error - Error fetching URL: 
>   https://download.eclipse.org/jgit/site/5.4.3.201909031940-r/apidocs/
>   1 error
> 
> I could reproduce that locally by running:
> 
>   `bazelisk build --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 -- 
>   javabase=@bazel_tools//tools/jdk:remote_jdk11 -- 
>   host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 -- 
>   java_toolchain=@bazel_tools//tools/jdk:toolchain_java11 --spawn_strategy=standalone -- 
>   genrule_strategy=standalone plugins:core release api`
> 
> Running `bazelisk build plugins:core release api` works though. Funnily enough the same happens without the change adding the support for the jdk11 toolset. Any ideas?

Not really, besides that:

  https://download.eclipse.org/jgit/site/5.4.3.201909031940-r/apidocs/

is really doesn't exist. @Matthiasm what is the right URL to fetch JGit apidoc?

Patch-set: 12
Reviewer: Gerrit User 1004034 <1004034@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>