Update nodejs to 6.x
Reason is because it keeps failing with

/usr/lib/node_modules/web-component-tester/node_modules/polyserve/lib/compile-middleware.js:126
    const [majorVersion, minorVersion] = versionSplit.map((v) => v ? parseInt(v, 10) : -1);
          ^

SyntaxError: Unexpected token [

https://gerrit-ci.gerritforge.com/job/Gerrit-verifier-bazel/16544/console

I suspect this is because of nodejs 4.x. Since polyserve doint test
against nodejs 4.x https://github.com/Polymer/polyserve/blob/master/.travis.yml

Change-Id: Idd8889841eac17dec506bbd5ecac93a2b847f161