Update patch set 12
Patch Set 12:

OK, I found one problem during javadoc generation: [1]. It is using wrong javadoc:

  external/local_jdk/bin/javadoc -Xdoclint:-missing -protected -encoding UTF-8 [...]

while it must use javadoc from remote JDK, e.g.:

  $ $(bazel info output_base)/external/remotejdk11_linux/bin/javadoc --version
  javadoc 11.0.1

That why we are seeing:

  import javax.annotation.processing.Generated;
                                  ^
  symbol:   class Generated
  location: package javax.annotation.processing

  AutoAnnotation_ConfigAnnotationParser_newGerritConfig.java:6: error: cannot find symbol
@Generated("com.google.auto.value.processor.AutoAnnotationProcessor")
 ^
  symbol: class Generated

* [1] http://paste.openstack.org/show/775771/

Patch-set: 12
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>